import { nanaVenues } from '@tobi/game-data';
import type { AmbientZone } from '../../audio/spatial-ambience.js';
export const nanaAudioZones: readonly AmbientZone[] = [
  {
    id: 'sukhumvit-traffic',
    x: 5,
    y: 0,
    z: -62,
    radius: 80,
    kind: 'traffic',
    tempo: 2.4,
    note: 80,
    volume: 0.05,
  },
  {
    id: 'bts-station',
    x: 22,
    y: 8,
    z: -54,
    radius: 55,
    kind: 'train',
    tempo: 2,
    note: 140,
    volume: 0.05,
  },
  {
    id: 'soi-voices',
    x: 0,
    y: 0,
    z: -23,
    radius: 35,
    kind: 'voices',
    tempo: 3.4,
    note: 190,
    volume: 0.025,
  },
  {
    id: 'courtyard-bar-west',
    x: -9,
    y: 0,
    z: 24,
    radius: 30,
    kind: 'music',
    tempo: 0.52,
    note: 146,
    volume: 0.026,
  },
  {
    id: 'courtyard-bar-east',
    x: 9,
    y: 0,
    z: 40,
    radius: 30,
    kind: 'music',
    tempo: 0.46,
    note: 196,
    volume: 0.026,
  },
  ...nanaVenues
    .filter((v) => v.mode !== 'facade')
    .map((v, i) => ({
      id: v.id,
      x: v.side * 26,
      y: v.floor * 4.8,
      z: v.z,
      radius: 27,
      kind: 'music' as const,
      tempo: 0.38 + (i % 5) * 0.035,
      note: [110, 146.83, 164.81, 196, 220][i % 5]!,
      volume: v.signature ? 0.065 : 0.035,
    })),
];
