/** Append a lesson when introducing a player action; each required world prop lives in tutorial-scene. */
export const tutorialLessons = [
  {
    id: 'walk',
    metric: 'distance',
    threshold: 3,
    title: 'BEWEGE TOBI',
    key: 'W A S D',
    body: 'Gehe ein paar Schritte. Die Pfeiltasten funktionieren ebenfalls.',
  },
  {
    id: 'camera',
    metric: 'camera',
    threshold: 0.5,
    title: 'SCHAU DICH UM',
    key: 'MAUS',
    body: 'Bewege die Maus. Ohne Mausfang: linke Maustaste halten und ziehen. Die Kamera dreht sich rundherum.',
  },
  {
    id: 'jump',
    metric: 'jumps',
    threshold: 1,
    title: 'SPRING!',
    key: 'SPACE',
    body: 'Drücke die Leertaste. Niedrige Hindernisse lassen sich überspringen.',
  },
  {
    id: 'sprint',
    metric: 'sprint',
    threshold: 1,
    title: 'GIB GAS',
    key: 'SHIFT + W',
    body: 'Halte Shift beim Laufen. Sprint verbraucht Energie; jede Flasche füllt sie wieder auf.',
  },
  {
    id: 'collect',
    metric: 'bottles',
    threshold: 5,
    cumulative: true,
    title: 'SAMMLE DIE FÜNF FLASCHEN',
    key: 'WASD',
    body: 'Folge dem hellen Weg nach Norden. Lauf direkt über die Flaschen: Tobi trinkt automatisch.',
  },
  {
    id: 'drink',
    metric: 'drinks',
    threshold: 1,
    cumulative: true,
    title: 'GLUCK, GLUCK …',
    key: 'KURZ WARTEN',
    body: 'Die leere Flasche bleibt nach dem Trinken in der Hand. Sein Gang wird dabei zunehmend wacklig.',
  },
  {
    id: 'throw',
    metric: 'throws',
    threshold: 1,
    title: 'DRÜCKE G ZUM WERFEN',
    key: 'G',
    body: 'Drehe Tobi durch eine kurze Bewegung zum Ziel. Er wirft in seine Blickrichtung – unabhängig von der Kamera.',
  },
  {
    id: 'taunt',
    metric: 'taunts',
    threshold: 1,
    title: 'DRÜCKE R ZUM ANPÖBELN',
    key: 'R',
    body: 'Rufe dem Übungspartner beim violetten Schild etwas zu. Im Abenteuer macht das die Polizei aufmerksam.',
  },
  {
    id: 'cover',
    metric: 'cover',
    threshold: 2,
    title: 'VERSTECKE DICH',
    key: 'DECKUNG',
    body: 'Gehe rechts hinter die grüne Sichtschutzwand. Bleibe zwei Sekunden ausser Sicht des Übungspartners.',
  },
  {
    id: 'sit',
    metric: 'seated',
    threshold: 1,
    title: 'SETZ DICH',
    key: 'E',
    body: 'Gehe am nördlichen Ende um die grüne Wand, dann zur Bank links neben dir. Drücke dort E und bleibe kurz sitzen.',
  },
  {
    id: 'stand',
    metric: 'stoodUp',
    threshold: 1,
    title: 'STEH WIEDER AUF',
    key: 'E',
    body: 'Drücke erneut E. Danach erreichst du CASA TOBI vorne am Ende des Wegs und schliesst mit E ab.',
  },
] as const;
export const tutorialLayout = {
  trainer: { x: 0, y: 1.5, z: 7 },
  coverRoute: [
    { x: 0, y: 1.1, z: 3 },
    { x: 4.5, y: 1.1, z: 3 },
    { x: 4.5, y: 1.1, z: 7 },
  ],
  cover: { x: 4.5, y: 1.1, z: 7 },
  seatRoute: [
    { x: 4.5, y: 1.1, z: 11 },
    { x: 0.8, y: 1.1, z: 11 },
  ],
  seat: {
    id: 'tutorial-seat',
    label: 'ÜBUNGSBANK · SITZEN',
    kind: 'seat' as const,
    position: { x: 2.3, y: 1.45, z: 14 },
    exit: { x: 0.8, y: 1.1, z: 14 },
    yaw: Math.PI / 2,
  },
} as const;
