/** Zurich's lake basin, compressed to a playable 104 x 108 metre plate.
 * The parade follows the real order Utoquai, Bellevue, Quaibruecke, Buerkliplatz, Hafendamm Enge.
 * Every rectangle here is authored once and consumed by both the scene builder and the
 * placement test, so a bottle can never end up inside the Grossmuenster or in the lake.
 */
export const zurichLayout = {
  ground: { minX: -52, maxX: 52, minZ: -54, maxZ: 54 },
  water: [
    { id: 'zuerichsee', minX: -25, maxX: 15, minZ: -54, maxZ: -11.2 },
    { id: 'limmat_sued', minX: -16, maxX: 2, minZ: -1.8, maxZ: 11.8 },
    { id: 'limmat_nord', minX: -16, maxX: 2, minZ: 17.2, maxZ: 54 },
  ],
  bridges: [
    { id: 'quaibruecke', minX: -25, maxX: 15, minZ: -11, maxZ: -2 },
    { id: 'muensterbruecke', minX: -16, maxX: 2, minZ: 12, maxZ: 17 },
  ],
  blocks: [
    {
      id: 'seefeld_a',
      x: 32,
      z: -18,
      width: 8,
      depth: 8,
      height: 13,
      style: 'stone',
      label: 'SEEFELD',
    },
    { id: 'seefeld_b', x: 45, z: -20, width: 9, depth: 9, height: 15, style: 'stone', label: '' },
    { id: 'seefeld_c', x: 46, z: -32, width: 8, depth: 10, height: 14, style: 'stone', label: '' },
    { id: 'seefeld_d', x: 44, z: -44, width: 8, depth: 8, height: 12, style: 'stone', label: '' },
    {
      id: 'china_garden',
      x: 34,
      z: -48,
      width: 6,
      depth: 6,
      height: 5,
      style: 'pavilion',
      label: 'CHINAGARTEN',
    },
    {
      id: 'opernhaus',
      x: 40,
      z: 8,
      width: 13,
      depth: 11,
      height: 13,
      style: 'grand',
      label: 'OPERNHAUS',
    },
    {
      id: 'bellevue_block',
      x: 26,
      z: 12,
      width: 10,
      depth: 10,
      height: 16,
      style: 'stone',
      label: 'BELLEVUE',
    },
    {
      id: 'bahnhofstrasse_1',
      x: -45,
      z: 4,
      width: 10,
      depth: 10,
      height: 15,
      style: 'stone',
      label: 'BAHNHOFSTRASSE',
    },
    {
      id: 'bahnhofstrasse_2',
      x: -45,
      z: 17,
      width: 10,
      depth: 10,
      height: 17,
      style: 'stone',
      label: '',
    },
    {
      id: 'bahnhofstrasse_3',
      x: -45,
      z: 30,
      width: 10,
      depth: 10,
      height: 15,
      style: 'stone',
      label: '',
    },
    {
      id: 'bahnhofstrasse_4',
      x: -45,
      z: 43,
      width: 10,
      depth: 10,
      height: 16,
      style: 'stone',
      label: '',
    },
    {
      id: 'hauptbahnhof',
      x: -34,
      z: 50,
      width: 22,
      depth: 9,
      height: 17,
      style: 'grand',
      label: 'HAUPTBAHNHOF',
    },
    {
      id: 'altstadt_w1',
      x: -22,
      z: 26,
      width: 7,
      depth: 8,
      height: 14,
      style: 'oldtown',
      label: '',
    },
    {
      id: 'altstadt_w2',
      x: -22,
      z: 36,
      width: 7,
      depth: 8,
      height: 15,
      style: 'oldtown',
      label: '',
    },
    {
      id: 'altstadt_w3',
      x: -21,
      z: 46,
      width: 8,
      depth: 8,
      height: 13,
      style: 'oldtown',
      label: '',
    },
    {
      id: 'fraumuenster',
      x: -20,
      z: 14,
      width: 9,
      depth: 10,
      height: 11,
      style: 'church',
      label: 'FRAUMUENSTER',
    },
    {
      id: 'grossmuenster',
      x: 11,
      z: 18,
      width: 11,
      depth: 12,
      height: 13,
      style: 'church',
      label: 'GROSSMUENSTER',
    },
    {
      id: 'niederdorf_1',
      x: 11,
      z: 32,
      width: 9,
      depth: 9,
      height: 15,
      style: 'oldtown',
      label: 'NIEDERDORF',
    },
    {
      id: 'niederdorf_2',
      x: 11,
      z: 42,
      width: 9,
      depth: 9,
      height: 14,
      style: 'oldtown',
      label: '',
    },
    {
      id: 'niederdorf_3',
      x: 12,
      z: 51,
      width: 9,
      depth: 8,
      height: 13,
      style: 'oldtown',
      label: '',
    },
    {
      id: 'hafen_schuppen',
      x: -45,
      z: -48,
      width: 7,
      depth: 5,
      height: 4,
      style: 'shed',
      label: 'HAFEN ENGE',
    },
  ],
  towers: [
    { id: 'fraumuenster_spitz', x: -20, z: 10, width: 3, depth: 3, height: 28 },
    { id: 'grossmuenster_nord', x: 7, z: 14, width: 3.2, depth: 3.2, height: 30 },
    { id: 'grossmuenster_sued', x: 7, z: 22, width: 3.2, depth: 3.2, height: 30 },
  ],
  loveMobiles: [
    { id: 'karl_fm', x: 17.5, z: -30, width: 3.6, depth: 7, height: 3.4 },
    { id: 'bellevue_bass', x: 26, z: -6, width: 3.6, depth: 7, height: 3.4 },
    { id: 'tobi_techno', x: -28, z: -29, width: 3.6, depth: 7, height: 3.4 },
    { id: 'buerkli_beat', x: -35, z: -17, width: 3.6, depth: 7, height: 3.4 },
  ],
  /** Walkable promenades and squares, painted on top of the ground plate. */
  promenades: [
    { id: 'utoquai', x: 20.5, z: -30.5, width: 11, depth: 39 },
    { id: 'bellevue', x: 22.5, z: -4, width: 15, depth: 16 },
    { id: 'sechselaeutenplatz', x: 36, z: -7, width: 20, depth: 18 },
    { id: 'buerkliplatz', x: -32.5, z: -6, width: 15, depth: 16 },
    { id: 'general_guisan_quai', x: -32.5, z: -30, width: 15, depth: 32 },
    { id: 'hafendamm_enge', x: -40, z: -46, width: 12, depth: 8 },
    { id: 'bahnhofstrasse', x: -34, z: 21, width: 12, depth: 46 },
    { id: 'limmatquai', x: 3.5, z: 26, width: 3, depth: 52 },
  ],
  /** Parade route centre line: seeds the dancing crowd and is walked by the route test. */
  route: [
    { x: 20, z: -46 },
    { x: 21, z: -14 },
    { x: 22, z: -6 },
    { x: 14, z: -6.5 },
    { x: -24, z: -6.5 },
    { x: -32, z: -6 },
    { x: -32, z: -30 },
    { x: -40, z: -44 },
  ],
} as const;
